#!/bin/bash
set -x

tfversion(){
  echo "Checking for tfswitch file"
  if test -f ".tfswitchrc";
    then
      echo "Tfswitch file exists"
      version=$(cat .tfswitchrc)
      echo "Terraform Version: ${version}"
      asdf shell terraform $version
    else
      echo "No tfswitch file exists"
  fi
  terraform version
}
